'use client'

import { useState } from 'react'
import type { PlanResponse, PlanTopic, TriageData } from '@/lib/sat-types'
import { deriveTimes } from '@/lib/time-utils'
import { downloadFormulaSheetPdf } from '@/lib/formula-pdf'
import { BreathingAnimation } from './breathing-animation'
import { SleepBanner } from './sleep-banner'
import { SummaryCard } from './summary-card'
import { TopicCard } from './topic-card'

interface Props {
  response: PlanResponse
  triage: TriageData
  topics: PlanTopic[]
  completed: Set<string>
  sprint: boolean
  voiceEnabled: boolean
  speak: (text: string) => void
  onComplete: (topicName: string, confident: boolean) => void
  onReorder: (index: number, dir: -1 | 1) => void
  onActiveStep: (text: string) => void
  onContinue: () => void
}

export function StudyPlan({
  response,
  triage,
  topics,
  completed,
  sprint,
  voiceEnabled,
  speak,
  onComplete,
  onReorder,
  onActiveStep,
  onContinue,
}: Props) {
  const { plan } = response
  const [breakOpen, setBreakOpen] = useState(false)
  const times = deriveTimes(triage.testStartTime)

  function handleComplete(topicName: string, confident: boolean) {
    onComplete(topicName, confident)
    if (confident && !sprint) {
      setBreakOpen(true)
    }
  }

  return (
    <div className="animate-fade-in mx-auto flex w-full max-w-3xl flex-col gap-5">
      {sprint && (
        <div className="rounded-xl border border-red-400 bg-red-600 px-4 py-3 text-white">
          <p className="text-sm font-bold">Sprint mode</p>
          <p className="text-xs leading-relaxed">
            We cut everything non-essential. Do these two things only.
          </p>
        </div>
      )}

      {response.source === 'fallback' && response.note && (
        <div className="rounded-xl border border-amber-400 bg-amber-50 px-4 py-3 dark:bg-amber-950/30">
          <p className="text-sm font-medium text-amber-700 dark:text-amber-300">{response.note}</p>
        </div>
      )}

      {response.source === 'ai' && response.provider && (
        <p className="text-center text-xs text-muted-foreground">
          Plan generated by {response.provider}
        </p>
      )}

      <SummaryCard plan={plan} triage={triage} />

      {/* Responsible AI banner */}
      <div className="rounded-xl border border-border bg-muted/50 px-4 py-3">
        <p className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
          <span className="ti ti-info-circle mt-0.5 shrink-0" aria-hidden="true" />
          This plan is based on general SAT patterns and your self-reported weak areas. Estimated
          score impacts are approximations. Use your own judgment.
        </p>
      </div>

      {times && (
        <SleepBanner
          sleepDeadlineMinutes={times.sleepDeadlineMinutes}
          wakeUpLabel={times.wakeUpLabel}
          sleepLabel={times.sleepDeadlineLabel}
        />
      )}

      {/* Formula sheet download */}
      <section className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3">
          <span
            className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-muted text-foreground"
            aria-hidden="true"
          >
            <span className="ti ti-math-function text-xl" />
          </span>
          <div>
            <h3 className="text-sm font-bold text-foreground">SAT formula &amp; rule sheet</h3>
            <p className="text-xs text-muted-foreground">
              Download every must-know math formula and grammar rule as a printable PDF.
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={downloadFormulaSheetPdf}
          className="flex min-h-[44px] shrink-0 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90"
        >
          <span className="ti ti-download text-base" aria-hidden="true" />
          Download PDF
        </button>
      </section>

      <div className="flex flex-col gap-4">
        {topics.map((topic, i) => (
          <TopicCard
            key={topic.name}
            topic={topic}
            index={i}
            total={topics.length}
            completed={completed.has(topic.name)}
            voiceEnabled={voiceEnabled}
            speak={speak}
            onComplete={(confident) => handleComplete(topic.name, confident)}
            onReorder={(dir) => onReorder(i, dir)}
            onActiveStep={onActiveStep}
          />
        ))}
      </div>

      {/* Skip topics */}
      {plan.skip_topics.length > 0 && (
        <section className="rounded-2xl border border-border bg-card p-4">
          <h3 className="flex items-center gap-2 text-sm font-bold">
            <span className="ti ti-circle-minus text-muted-foreground" aria-hidden="true" />
            Skip these tonight
          </h3>
          <ul className="mt-3 flex flex-col gap-2">
            {plan.skip_topics.map((s) => (
              <li key={s.name} className="text-sm">
                <span className="font-semibold">{s.name}.</span>{' '}
                <span className="text-muted-foreground">{s.reason}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Quick tips */}
      {(plan.top_math_tips.length > 0 || plan.top_rw_tips.length > 0) && (
        <section className="grid grid-cols-1 gap-3">
          {plan.top_math_tips.length > 0 && (
            <TipCard title="Top Math reminders" tips={plan.top_math_tips} icon="ti-math" />
          )}
          {plan.top_rw_tips.length > 0 && (
            <TipCard title="Top R&W reminders" tips={plan.top_rw_tips} icon="ti-book-2" />
          )}
        </section>
      )}

      <button
        type="button"
        onClick={onContinue}
        className="flex min-h-[52px] w-full items-center justify-center gap-2 rounded-xl bg-foreground text-base font-semibold text-background"
      >
        Go to my night-before checklist
        <span className="ti ti-arrow-right" aria-hidden="true" />
      </button>

      {/* Break overlay */}
      {breakOpen && (
        <div className="fixed inset-0 z-50 flex flex-col items-center justify-center gap-6 bg-background/95 px-6 backdrop-blur">
          <div>
            <p className="text-center text-xs font-medium uppercase tracking-widest text-muted-foreground">
              5-minute reset
            </p>
            <h2 className="mt-1 text-center text-xl font-bold">Nice work. Let’s breathe.</h2>
          </div>
          <BreathingAnimation
            cycles={3}
            speak={voiceEnabled ? speak : undefined}
            showSkip
            onSkip={() => setBreakOpen(false)}
            onComplete={() => {}}
            completeMessage="Good. Now go back to your plan. You’ve got this."
          />
          <button
            type="button"
            onClick={() => setBreakOpen(false)}
            className="min-h-[48px] rounded-xl bg-primary px-6 text-sm font-semibold text-primary-foreground"
          >
            Back to my plan
          </button>
        </div>
      )}
    </div>
  )
}

function TipCard({ title, tips, icon }: { title: string; tips: string[]; icon: string }) {
  return (
    <div className="rounded-2xl border border-border bg-card p-4">
      <h3 className="flex items-center gap-2 text-sm font-bold">
        <span className={`${icon} ti text-primary`} aria-hidden="true" />
        {title}
      </h3>
      <ul className="mt-2 flex flex-col gap-1.5">
        {tips.map((t, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
            <span className="ti ti-check mt-0.5 text-emerald-500" aria-hidden="true" />
            {t}
          </li>
        ))}
      </ul>
    </div>
  )
}
