const FAQS = [
  {
    q: 'Is it really free?',
    a: 'Yes. SAT Emergency Room is completely free to use. There is no account, no credit card, and no paywall. We built it because good last-minute help should not be a luxury.',
  },
  {
    q: 'Do I need to create an account?',
    a: 'No. You can jump straight in and get your plan. We do not ask for your name, email, or any login. Your answers stay in your browser.',
  },
  {
    q: 'Will this actually raise my score the night before?',
    a: 'No tool can promise points overnight, but focused, high-yield review and a calm head genuinely help. We prioritize the topics most likely to move your score and keep you from burning out before test day.',
  },
  {
    q: 'Is this affiliated with the College Board?',
    a: 'No. We are an independent study tool and are not affiliated with, endorsed by, or sponsored by the College Board. SAT is a registered trademark of the College Board.',
  },
  {
    q: 'Where does the practice come from?',
    a: 'Questions, explanations, and plans are generated by AI and curated from proven high-yield SAT topics. They are designed to mirror the real test format, but they are practice material, not official exam questions.',
  },
  {
    q: 'What if I feel like I am panicking?',
    a: 'Tap the panic button anytime. It walks you through a short breathing exercise and grounding reminders, then eases you back into your plan one small step at a time.',
  },
]

export function Faq() {
  return (
    <section id="faq">
      <div className="mx-auto w-full max-w-3xl px-5 py-20 lg:px-8 lg:py-28">
        <div className="flex flex-col gap-4 text-center">
          <span className="text-sm font-bold uppercase tracking-wider text-primary">
            Questions
          </span>
          <h2 className="text-balance font-serif text-4xl font-normal tracking-tight sm:text-5xl">
            Everything you might be wondering
          </h2>
        </div>

        <div className="mt-10 flex flex-col gap-3">
          {FAQS.map((item) => (
            <details
              key={item.q}
              className="group rounded-2xl border border-border bg-card p-5 transition-colors open:border-primary/40"
            >
              <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-base font-semibold">
                {item.q}
                <span
                  className="ti ti-plus shrink-0 text-lg text-primary transition-transform group-open:rotate-45"
                  aria-hidden="true"
                />
              </summary>
              <p className="mt-3 text-pretty leading-relaxed text-muted-foreground">{item.a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  )
}
