'use client'

import { useRef, useState } from 'react'
import type { DashboardView } from '@/lib/sat-types'
import { cn } from '@/lib/utils'

// ── FAQ data ───────────────────────────────────────────────────────────────

interface FaqEntry {
  category: string
  q: string
  a: string
}

const FAQ: FaqEntry[] = [
  // Getting started
  {
    category: 'Getting started',
    q: 'What is SAT Sage?',
    a: 'SAT Sage is an AI-powered SAT prep companion designed for last-minute studying. It generates a personalized study plan, runs practice drills, explains mistakes with an AI tutor, and helps you stay calm the night before your exam.',
  },
  {
    category: 'Getting started',
    q: 'Do I need an account?',
    a: 'No account is required to use the core features. Your progress is stored locally in your browser. Creating an account lets you sync across devices and access community features.',
  },
  {
    category: 'Getting started',
    q: 'How does the AI study plan work?',
    a: 'After a quick triage (panic level, time budget, weak areas, and current scores), Sage generates a prioritized topic list with estimated score impact. Topics are ranked by how much they can move your score in the time available.',
  },
  // Practice & diagnostics
  {
    category: 'Practice & diagnostics',
    q: 'What is the AI Diagnostic?',
    a: 'The diagnostic is a short adaptive test that identifies your weak areas before and after your study session, so you can measure real improvement.',
  },
  {
    category: 'Practice & diagnostics',
    q: 'Where do the practice questions come from?',
    a: 'Questions are generated by AI and are modelled on real Digital SAT format, difficulty distribution, and topic coverage. They are not official College Board questions.',
  },
  {
    category: 'Practice & diagnostics',
    q: 'How accurate is the estimated SAT score?',
    a: 'The estimated score is a rough projection based on your practice accuracy and weak area coverage. Treat it as a directional signal, not a guaranteed prediction.',
  },
  // AI features
  {
    category: 'AI features',
    q: 'How does the AI Whiteboard work?',
    a: 'The Whiteboard AI lets you write a math or reading question on a virtual canvas. Sage then writes a step-by-step solution directly on the board, narrating each step.',
  },
  {
    category: 'AI features',
    q: 'What is the AI Learning Brain?',
    a: 'The AI Learning Brain tracks your mistake patterns over time and surfaces the concepts you keep getting wrong. It builds a personalised "mistake memory" so you can review your weakest spots efficiently.',
  },
  {
    category: 'AI features',
    q: 'Can I change how Sage communicates?',
    a: 'Yes. In Settings > AI & Voice you can choose from six AI personalities: Encouraging, Direct, Socratic, Friendly, Formal, and Humorous.',
  },
  // Study Rooms
  {
    category: 'Study rooms',
    q: 'What are Study Rooms?',
    a: 'Study Rooms are live collaborative sessions where up to 8 students can practice together, chat, and share a whiteboard in real time.',
  },
  {
    category: 'Study rooms',
    q: 'Do Study Rooms require an account?',
    a: 'You need a display name to join. Account sign-in is required to host a room and save session history.',
  },
  // Premium
  {
    category: 'Premium',
    q: 'What does Premium include?',
    a: 'Premium (Pro plan) includes unlimited Whiteboard AI sessions, unlimited AI Tutor questions, advanced analytics, offline mode, and the ability to publish questions to the community.',
  },
  {
    category: 'Premium',
    q: 'Is there a free trial?',
    a: 'Yes. Pro includes a 7-day free trial. No credit card required until the trial ends.',
  },
]

// ── AI support chat ───────────────────────────────────────────────────────

interface ChatMessage {
  role: 'user' | 'ai'
  text: string
}

const CANNED_RESPONSES: Record<string, string> = {
  default:
    'I\'m the SAT Sage support assistant. I can help with questions about features, study plans, practice sessions, and account settings. What would you like to know?',
  plan:
    'Your study plan is generated from your triage answers. To rebuild it with updated information, go to Dashboard > Study Plan and tap "Rebuild plan" at the bottom.',
  practice:
    'Practice drills in the Practice tab are AI-generated SAT-style questions. Each question includes a full explanation. Your accuracy is tracked in Progress.',
  flashcard:
    'Flashcards are found in the Flashcards tab. You can filter by section (Math or Reading & Writing) and by your weak topics from the triage.',
  whiteboard:
    'The Whiteboard AI is a full-screen experience at /whiteboard. You can sketch a question or type it, and Sage will write a step-by-step solution on the board.',
  premium:
    'SAT Sage Pro unlocks unlimited Whiteboard AI, Ask AI Tutor, advanced analytics, and offline mode. See the Premium page for pricing.',
  account:
    'Account and privacy settings are in the Settings section of your dashboard sidebar.',
}

function getAiReply(input: string): string {
  const lower = input.toLowerCase()
  if (lower.includes('plan') || lower.includes('study')) return CANNED_RESPONSES.plan
  if (lower.includes('practice') || lower.includes('drill') || lower.includes('question')) return CANNED_RESPONSES.practice
  if (lower.includes('flashcard') || lower.includes('card')) return CANNED_RESPONSES.flashcard
  if (lower.includes('whiteboard') || lower.includes('tutor')) return CANNED_RESPONSES.whiteboard
  if (lower.includes('premium') || lower.includes('pro') || lower.includes('price')) return CANNED_RESPONSES.premium
  if (lower.includes('account') || lower.includes('setting') || lower.includes('password')) return CANNED_RESPONSES.account
  return CANNED_RESPONSES.default
}

// ── Sub-components ────────────────────────────────────────────────────────

function FaqItem({ entry }: { entry: FaqEntry }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left"
        aria-expanded={open}
      >
        <span className="text-sm font-semibold text-foreground">{entry.q}</span>
        <i
          className={cn(
            'ti shrink-0 text-sm text-muted-foreground transition-transform',
            open ? 'ti-chevron-up' : 'ti-chevron-down',
          )}
          aria-hidden="true"
        />
      </button>
      {open && (
        <div className="border-t border-border px-5 py-4">
          <p className="text-sm leading-relaxed text-muted-foreground">{entry.a}</p>
        </div>
      )}
    </div>
  )
}

// ── Main component ─────────────────────────────────────────────────────────

type HelpTab = 'faq' | 'chat' | 'bug' | 'feature'

interface HelpViewProps {
  onNavigate: (view: DashboardView) => void
}

export function HelpView({ onNavigate: _ }: HelpViewProps) {
  const [tab, setTab] = useState<HelpTab>('faq')
  const [faqSearch, setFaqSearch] = useState('')
  const [faqCategory, setFaqCategory] = useState('All')

  // Chat
  const [messages, setMessages] = useState<ChatMessage[]>([
    { role: 'ai', text: CANNED_RESPONSES.default },
  ])
  const [chatInput, setChatInput] = useState('')
  const [chatThinking, setChatThinking] = useState(false)
  const chatEndRef = useRef<HTMLDivElement>(null)

  // Bug report
  const [bugType, setBugType] = useState('visual')
  const [bugDesc, setBugDesc] = useState('')
  const [bugSubmitted, setBugSubmitted] = useState(false)

  // Feature request
  const [featureTitle, setFeatureTitle] = useState('')
  const [featureDesc, setFeatureDesc] = useState('')
  const [featureSubmitted, setFeatureSubmitted] = useState(false)

  // FAQ helpers
  const categories = ['All', ...Array.from(new Set(FAQ.map((f) => f.category)))]
  const filteredFaq = FAQ.filter((f) => {
    const matchCat = faqCategory === 'All' || f.category === faqCategory
    const matchSearch =
      faqSearch === '' ||
      f.q.toLowerCase().includes(faqSearch.toLowerCase()) ||
      f.a.toLowerCase().includes(faqSearch.toLowerCase())
    return matchCat && matchSearch
  })

  // Chat send
  function sendMessage() {
    const text = chatInput.trim()
    if (!text) return
    setMessages((m) => [...m, { role: 'user', text }])
    setChatInput('')
    setChatThinking(true)
    setTimeout(() => {
      setMessages((m) => [...m, { role: 'ai', text: getAiReply(text) }])
      setChatThinking(false)
      requestAnimationFrame(() => chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }))
    }, 900)
  }

  const TABS: { id: HelpTab; label: string; icon: string }[] = [
    { id: 'faq',     label: 'FAQs',           icon: 'ti-help-circle' },
    { id: 'chat',    label: 'AI Support',      icon: 'ti-robot' },
    { id: 'bug',     label: 'Report a bug',    icon: 'ti-bug' },
    { id: 'feature', label: 'Feature request', icon: 'ti-bulb' },
  ]

  return (
    <div className="animate-fade-in flex flex-col gap-5">

      {/* Header */}
      <div className="flex flex-col gap-1">
        <h1 className="text-xl font-bold text-foreground">Help Center</h1>
        <p className="text-sm text-muted-foreground">
          Find answers, report issues, and share ideas with the SAT Sage team.
        </p>
      </div>

      {/* Tab strip */}
      <div className="flex gap-1 overflow-x-auto no-scrollbar rounded-xl border border-border bg-card p-1">
        {TABS.map((t) => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTab(t.id)}
            aria-current={tab === t.id ? 'page' : undefined}
            className={cn(
              'flex shrink-0 items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors',
              tab === t.id
                ? 'bg-primary text-primary-foreground'
                : 'text-muted-foreground hover:bg-muted hover:text-foreground',
            )}
          >
            <i className={cn('ti', t.icon)} aria-hidden="true" />
            {t.label}
          </button>
        ))}
      </div>

      {/* ── FAQ ──────────────────────────────────────────────────────── */}
      {tab === 'faq' && (
        <div className="flex flex-col gap-4">
          {/* Search */}
          <div className="relative">
            <i className="ti ti-search absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" aria-hidden="true" />
            <input
              type="search"
              value={faqSearch}
              onChange={(e) => setFaqSearch(e.target.value)}
              placeholder="Search FAQs..."
              aria-label="Search FAQs"
              className="w-full rounded-xl border border-border bg-card py-2.5 pl-9 pr-4 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>

          {/* Category chips */}
          <div className="flex gap-2 overflow-x-auto no-scrollbar pb-1">
            {categories.map((cat) => (
              <button
                key={cat}
                type="button"
                onClick={() => setFaqCategory(cat)}
                aria-pressed={faqCategory === cat}
                className={cn(
                  'shrink-0 rounded-full border px-3.5 py-1 text-xs font-medium transition-colors',
                  faqCategory === cat
                    ? 'border-primary bg-primary text-primary-foreground'
                    : 'border-border bg-card text-muted-foreground hover:border-primary/40 hover:text-foreground',
                )}
              >
                {cat}
              </button>
            ))}
          </div>

          {/* FAQ list */}
          {filteredFaq.length === 0 ? (
            <div className="flex flex-col items-center gap-2 rounded-2xl border border-dashed border-border bg-card py-12 text-center">
              <i className="ti ti-search-off text-3xl text-muted-foreground" aria-hidden="true" />
              <p className="text-sm text-muted-foreground">No results for &ldquo;{faqSearch}&rdquo;</p>
            </div>
          ) : (
            <div className="flex flex-col gap-2">
              {filteredFaq.map((f, i) => (
                <FaqItem key={`${f.category}-${i}`} entry={f} />
              ))}
            </div>
          )}
        </div>
      )}

      {/* ── AI support chat ───────────────────────────────────────────── */}
      {tab === 'chat' && (
        <div className="flex flex-col gap-4">
          <div
            className="flex h-96 flex-col gap-3 overflow-y-auto rounded-2xl border border-border bg-card p-4"
            aria-label="Support chat"
            aria-live="polite"
          >
            {messages.map((m, i) => (
              <div
                key={i}
                className={cn(
                  'flex max-w-[85%] flex-col gap-1',
                  m.role === 'user' ? 'self-end items-end' : 'self-start items-start',
                )}
              >
                {m.role === 'ai' && (
                  <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
                    <i className="ti ti-robot" aria-hidden="true" />
                    Sage Support
                  </div>
                )}
                <div
                  className={cn(
                    'rounded-2xl px-4 py-3 text-sm leading-relaxed',
                    m.role === 'user'
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-muted text-foreground',
                  )}
                >
                  {m.text}
                </div>
              </div>
            ))}
            {chatThinking && (
              <div className="flex items-center gap-1.5 self-start text-xs text-muted-foreground">
                <i className="ti ti-robot" aria-hidden="true" />
                <span>Sage is thinking</span>
                <span className="flex gap-0.5">
                  {[0, 1, 2].map((n) => (
                    <span
                      key={n}
                      className="typing-dot h-1.5 w-1.5 rounded-full bg-muted-foreground"
                      style={{ animationDelay: `${n * 0.2}s` }}
                    />
                  ))}
                </span>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          <form
            onSubmit={(e) => { e.preventDefault(); sendMessage() }}
            className="flex gap-2"
          >
            <input
              type="text"
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              placeholder="Ask a question..."
              aria-label="Chat message"
              className="flex-1 rounded-xl border border-border bg-card px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
            <button
              type="submit"
              disabled={!chatInput.trim() || chatThinking}
              className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-40"
              aria-label="Send message"
            >
              <i className="ti ti-send" aria-hidden="true" />
            </button>
          </form>
          <p className="text-center text-xs text-muted-foreground">
            AI Support uses pattern matching. For complex issues, use Contact below.
          </p>
        </div>
      )}

      {/* ── Bug report ───────────────────────────────────────────────── */}
      {tab === 'bug' && (
        <div className="rounded-2xl border border-border bg-card p-6 shadow-sm">
          {bugSubmitted ? (
            <div className="flex flex-col items-center gap-3 py-8 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-secondary text-primary">
                <i className="ti ti-check text-2xl" aria-hidden="true" />
              </div>
              <p className="text-base font-semibold text-foreground">Bug report submitted</p>
              <p className="text-sm text-muted-foreground">
                Thank you. We review all reports and will follow up if we need more information.
              </p>
              <button
                type="button"
                onClick={() => { setBugSubmitted(false); setBugDesc('') }}
                className="mt-2 text-sm text-primary hover:underline"
              >
                Submit another report
              </button>
            </div>
          ) : (
            <form
              onSubmit={(e) => { e.preventDefault(); if (bugDesc.trim()) setBugSubmitted(true) }}
              className="flex flex-col gap-4"
            >
              <div>
                <label className="mb-1.5 block text-sm font-semibold text-foreground">
                  Bug type
                </label>
                <select
                  value={bugType}
                  onChange={(e) => setBugType(e.target.value)}
                  aria-label="Bug type"
                  className="w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                >
                  <option value="visual">Visual / display issue</option>
                  <option value="crash">App crash or freeze</option>
                  <option value="data">Incorrect data or calculation</option>
                  <option value="ai">AI gave a wrong answer</option>
                  <option value="audio">Voice / audio issue</option>
                  <option value="other">Other</option>
                </select>
              </div>

              <div>
                <label className="mb-1.5 block text-sm font-semibold text-foreground">
                  Describe the bug
                </label>
                <textarea
                  value={bugDesc}
                  onChange={(e) => setBugDesc(e.target.value)}
                  rows={5}
                  placeholder="What happened? What did you expect to happen? What steps reproduce the issue?"
                  aria-label="Bug description"
                  className="w-full resize-none rounded-xl border border-border bg-background px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>

              <button
                type="submit"
                disabled={!bugDesc.trim()}
                className="self-start rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-40"
              >
                Submit report
              </button>
            </form>
          )}
        </div>
      )}

      {/* ── Feature request ───────────────────────────────────────────── */}
      {tab === 'feature' && (
        <div className="rounded-2xl border border-border bg-card p-6 shadow-sm">
          {featureSubmitted ? (
            <div className="flex flex-col items-center gap-3 py-8 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-secondary text-primary">
                <i className="ti ti-bulb text-2xl" aria-hidden="true" />
              </div>
              <p className="text-base font-semibold text-foreground">Idea submitted</p>
              <p className="text-sm text-muted-foreground">
                We read every feature request. Popular ideas make it onto our public roadmap.
              </p>
              <button
                type="button"
                onClick={() => { setFeatureSubmitted(false); setFeatureTitle(''); setFeatureDesc('') }}
                className="mt-2 text-sm text-primary hover:underline"
              >
                Submit another idea
              </button>
            </div>
          ) : (
            <form
              onSubmit={(e) => { e.preventDefault(); if (featureTitle.trim()) setFeatureSubmitted(true) }}
              className="flex flex-col gap-4"
            >
              <div>
                <label className="mb-1.5 block text-sm font-semibold text-foreground">
                  Feature title
                </label>
                <input
                  type="text"
                  value={featureTitle}
                  onChange={(e) => setFeatureTitle(e.target.value)}
                  placeholder="e.g. Dark mode, Offline flashcards..."
                  aria-label="Feature title"
                  className="w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>

              <div>
                <label className="mb-1.5 block text-sm font-semibold text-foreground">
                  Why would this help? (optional)
                </label>
                <textarea
                  value={featureDesc}
                  onChange={(e) => setFeatureDesc(e.target.value)}
                  rows={4}
                  placeholder="Describe the problem this feature would solve..."
                  aria-label="Feature description"
                  className="w-full resize-none rounded-xl border border-border bg-background px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>

              <button
                type="submit"
                disabled={!featureTitle.trim()}
                className="self-start rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-40"
              >
                Submit idea
              </button>
            </form>
          )}
        </div>
      )}

      {/* Contact links */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        {[
          { icon: 'ti-mail', label: 'Email us', sub: 'support@satsage.ai', href: 'mailto:support@satsage.ai' },
          { icon: 'ti-brand-twitter', label: 'Twitter/X', sub: '@SATSageApp', href: '#' },
          { icon: 'ti-file-description', label: 'Documentation', sub: 'Full feature docs', href: '#' },
        ].map((link) => (
          <a
            key={link.label}
            href={link.href}
            className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 shadow-sm transition-all hover:border-primary/30 hover:shadow-md"
          >
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary">
              <i className={cn('ti', link.icon, 'text-lg')} aria-hidden="true" />
            </div>
            <div className="min-w-0">
              <p className="text-sm font-semibold text-foreground">{link.label}</p>
              <p className="truncate text-xs text-muted-foreground">{link.sub}</p>
            </div>
            <i className="ti ti-chevron-right ml-auto shrink-0 text-muted-foreground" aria-hidden="true" />
          </a>
        ))}
      </div>

    </div>
  )
}
