import type { LanguageModel } from 'ai'

/**
 * Model access through the Vercel AI Gateway. The gateway is configured with
 * the project's AI_GATEWAY_API_KEY (zero-config for Google, OpenAI, Anthropic,
 * etc.), so we pass plain model strings to the AI SDK — no provider packages or
 * separate API keys required.
 *
 * Gemini leads the text/structured chain (per product requirement that the
 * study plan is generated by Gemini), with GPT-4o as an automatic backup if
 * Gemini errors or rate-limits.
 */

export const hasAIKeys =
  !!process.env.AI_GATEWAY_API_KEY || !!process.env.VERCEL_OIDC_TOKEN

export interface ModelAttempt {
  provider: string
  /** AI Gateway model id, accepted directly by the AI SDK as a LanguageModel. */
  model: LanguageModel
}

/** Text/structured generation chain. Gemini leads, GPT-4o backs it up. */
export function textModelChain(): ModelAttempt[] {
  return [
    { provider: 'Gemini 2.5 Flash', model: 'google/gemini-2.5-flash' },
    { provider: 'GPT-4o', model: 'openai/gpt-4o' },
    { provider: 'Gemini 2.0 Flash (backup)', model: 'google/gemini-2.0-flash' },
  ]
}

/** Vision chain for reading uploaded score reports. GPT-4o leads here. */
export function visionModelChain(): ModelAttempt[] {
  return [
    { provider: 'GPT-4o', model: 'openai/gpt-4o' },
    { provider: 'Gemini 2.5 Flash', model: 'google/gemini-2.5-flash' },
  ]
}
