import type { Flashcard } from './sat-types'

export const FLASHCARDS: Flashcard[] = [
  // Math
  {
    id: 'fc-m1',
    front: 'What is the quadratic formula?',
    back: 'x = (−b ± √(b² − 4ac)) / 2a — solves ax² + bx + c = 0.',
    category: 'Quadratics',
    section: 'Math',
  },
  {
    id: 'fc-m2',
    front: 'What does a positive discriminant tell you?',
    back: 'b² − 4ac > 0 means the quadratic has two distinct real roots.',
    category: 'Quadratics',
    section: 'Math',
  },
  {
    id: 'fc-m3',
    front: 'Slope between two points?',
    back: 'm = (y₂ − y₁) / (x₂ − x₁). Rise over run.',
    category: 'Linear',
    section: 'Math',
  },
  {
    id: 'fc-m4',
    front: 'Slopes of perpendicular lines?',
    back: 'Negative reciprocals. If one is 2, the other is −1/2.',
    category: 'Linear',
    section: 'Math',
  },
  {
    id: 'fc-m5',
    front: 'Sides of a 30-60-90 triangle?',
    back: 'x, x√3, 2x — opposite the 30°, 60°, and 90° angles.',
    category: 'Geometry',
    section: 'Math',
  },
  {
    id: 'fc-m6',
    front: 'Sides of a 45-45-90 triangle?',
    back: 'x, x, x√2 — the two legs are equal.',
    category: 'Geometry',
    section: 'Math',
  },
  {
    id: 'fc-m7',
    front: 'SOH-CAH-TOA stands for?',
    back: 'sin = opp/hyp, cos = adj/hyp, tan = opp/adj.',
    category: 'Trigonometry',
    section: 'Math',
  },
  {
    id: 'fc-m8',
    front: 'Percent change formula?',
    back: '(new − old) / old × 100. Negative means a decrease.',
    category: 'Statistics',
    section: 'Math',
  },
  {
    id: 'fc-m9',
    front: 'Exponential growth model?',
    back: 'y = a(1 + r)^t. Use (1 − r) for decay.',
    category: 'Statistics',
    section: 'Math',
  },
  {
    id: 'fc-m10',
    front: 'Vertex of y = a(x − h)² + k?',
    back: 'The vertex is at (h, k).',
    category: 'Quadratics',
    section: 'Math',
  },
  // Reading & Writing
  {
    id: 'fc-r1',
    front: 'How do you fix a comma splice?',
    back: 'Use a period, a semicolon, or a comma + FANBOYS conjunction.',
    category: 'Punctuation',
    section: 'Reading & Writing',
  },
  {
    id: 'fc-r2',
    front: "Difference between 'its' and 'it's'?",
    back: "'its' = possessive. 'it's' = it is / it has.",
    category: 'Punctuation',
    section: 'Reading & Writing',
  },
  {
    id: 'fc-r3',
    front: 'When do you use a colon?',
    back: 'After a complete sentence, to introduce a list or explanation.',
    category: 'Punctuation',
    section: 'Reading & Writing',
  },
  {
    id: 'fc-r4',
    front: 'FANBOYS conjunctions?',
    back: 'For, And, Nor, But, Or, Yet, So.',
    category: 'Grammar',
    section: 'Reading & Writing',
  },
  {
    id: 'fc-r5',
    front: 'Transition word for contrast?',
    back: 'However, but, yet, nevertheless, on the other hand.',
    category: 'Transitions',
    section: 'Reading & Writing',
  },
  {
    id: 'fc-r6',
    front: 'How do you answer an evidence question?',
    back: 'Pick the answer you can prove with a specific line in the passage.',
    category: 'Reading',
    section: 'Reading & Writing',
  },
  {
    id: 'fc-r7',
    front: 'Subject-verb agreement trick?',
    back: 'Ignore phrases between the subject and verb, then match number.',
    category: 'Grammar',
    section: 'Reading & Writing',
  },
  {
    id: 'fc-r8',
    front: 'What makes a good main-idea answer?',
    back: 'It captures the topic plus the author’s stance — not one detail.',
    category: 'Reading',
    section: 'Reading & Writing',
  },
]
