import type { PracticeQuestion } from './sat-types'

/**
 * A curated bank of SAT-style questions modeled on the digital SAT's format and
 * topic distribution. 30 Math + 30 Reading & Writing questions. These are
 * shuffled and split into 3 non-overlapping full-length practice tests
 * (10 Math + 10 Reading & Writing each) by `buildMockTests()`.
 */
export const MOCK_BANK: PracticeQuestion[] = [
  // ─────────────────────────── MATH (30) ───────────────────────────
  // Heart of Algebra
  {
    id: 'mock-m1',
    section: 'Math',
    topic: 'Linear equations',
    difficulty: 'Easy',
    prompt: 'If 5x − 3 = 2x + 12, what is the value of x?',
    choices: ['3', '5', '7', '9'],
    correctIndex: 1,
    explanation: 'Subtract 2x from both sides: 3x − 3 = 12. Add 3: 3x = 15, so x = 5.',
  },
  {
    id: 'mock-m2',
    section: 'Math',
    topic: 'Systems of equations',
    difficulty: 'Medium',
    prompt: 'If 2x + y = 11 and x − y = 1, what is the value of y?',
    choices: ['2', '3', '4', '5'],
    correctIndex: 1,
    explanation: 'Add the equations: 3x = 12, so x = 4. Substitute into x − y = 1: 4 − y = 1, so y = 3.',
  },
  {
    id: 'mock-m3',
    section: 'Math',
    topic: 'Linear models',
    difficulty: 'Easy',
    prompt:
      'A gym charges a $25 sign-up fee plus $15 per month. Which equation gives the total cost c after m months?',
    choices: ['c = 25m + 15', 'c = 15m + 25', 'c = 40m', 'c = 15m − 25'],
    correctIndex: 1,
    explanation: 'The monthly rate $15 multiplies the number of months m, and the $25 fee is a one-time constant: c = 15m + 25.',
  },
  {
    id: 'mock-m4',
    section: 'Math',
    topic: 'Slope',
    difficulty: 'Medium',
    prompt: 'What is the slope of the line passing through the points (1, 2) and (4, 11)?',
    choices: ['2', '3', '4', '9'],
    correctIndex: 1,
    explanation: 'Slope = (11 − 2) / (4 − 1) = 9 / 3 = 3.',
  },
  {
    id: 'mock-m5',
    section: 'Math',
    topic: 'Inequalities',
    difficulty: 'Medium',
    prompt: 'If 3x + 4 ≤ 19, what is the greatest possible integer value of x?',
    choices: ['4', '5', '6', '7'],
    correctIndex: 1,
    explanation: 'Subtract 4: 3x ≤ 15. Divide by 3: x ≤ 5. The greatest integer value is 5.',
  },
  // Problem Solving & Data Analysis
  {
    id: 'mock-m6',
    section: 'Math',
    topic: 'Percentages',
    difficulty: 'Easy',
    prompt: '30 is what percent of 120?',
    choices: ['20%', '25%', '30%', '40%'],
    correctIndex: 1,
    explanation: '30 / 120 = 0.25, which is 25%.',
  },
  {
    id: 'mock-m7',
    section: 'Math',
    topic: 'Percent change',
    difficulty: 'Medium',
    prompt: 'A product\'s price increased from $80 to $100. What was the percent increase?',
    choices: ['20%', '25%', '30%', '125%'],
    correctIndex: 1,
    explanation: 'Increase = $20. Percent increase = 20 / 80 = 0.25 = 25%.',
  },
  {
    id: 'mock-m8',
    section: 'Math',
    topic: 'Ratios',
    difficulty: 'Medium',
    prompt: 'In a class, the ratio of boys to girls is 5 to 3. If there are 24 girls, how many boys are there?',
    choices: ['15', '24', '40', '64'],
    correctIndex: 2,
    explanation: 'Each ratio unit = 24 / 3 = 8 students. Boys = 5 × 8 = 40.',
  },
  {
    id: 'mock-m9',
    section: 'Math',
    topic: 'Proportions',
    difficulty: 'Easy',
    prompt: 'If 3 pounds of apples cost $7.50, how much do 5 pounds cost at the same rate?',
    choices: ['$10.00', '$11.50', '$12.50', '$15.00'],
    correctIndex: 2,
    explanation: 'Price per pound = 7.50 / 3 = $2.50. For 5 pounds: 2.50 × 5 = $12.50.',
  },
  {
    id: 'mock-m10',
    section: 'Math',
    topic: 'Statistics',
    difficulty: 'Easy',
    prompt: 'What is the mean of the data set {12, 15, 18, 21, 24}?',
    choices: ['15', '18', '20', '21'],
    correctIndex: 1,
    explanation: 'Sum = 90. Divide by 5 values: 90 / 5 = 18.',
  },
  {
    id: 'mock-m11',
    section: 'Math',
    topic: 'Statistics',
    difficulty: 'Medium',
    prompt: 'What is the median of the data set {3, 7, 9, 12, 20}?',
    choices: ['7', '9', '10', '12'],
    correctIndex: 1,
    explanation: 'With five ordered values, the median is the middle value, which is 9.',
  },
  {
    id: 'mock-m12',
    section: 'Math',
    topic: 'Probability',
    difficulty: 'Medium',
    prompt: 'A bag contains 4 red marbles and 6 blue marbles. If one marble is drawn at random, what is the probability it is red?',
    choices: ['2/5', '3/5', '2/3', '1/2'],
    correctIndex: 0,
    explanation: 'P(red) = 4 / (4 + 6) = 4/10 = 2/5.',
  },
  {
    id: 'mock-m13',
    section: 'Math',
    topic: 'Data interpretation',
    difficulty: 'Easy',
    prompt: 'In a survey of 200 people, 25% said they prefer tea. How many people prefer tea?',
    choices: ['25', '50', '75', '150'],
    correctIndex: 1,
    explanation: '25% of 200 = 0.25 × 200 = 50 people.',
  },
  {
    id: 'mock-m14',
    section: 'Math',
    topic: 'Rates',
    difficulty: 'Easy',
    prompt: 'A car travels 240 miles in 4 hours. What is its average speed in miles per hour?',
    choices: ['40', '50', '60', '80'],
    correctIndex: 2,
    explanation: 'Speed = distance / time = 240 / 4 = 60 mph.',
  },
  {
    id: 'mock-m15',
    section: 'Math',
    topic: 'Linear models',
    difficulty: 'Medium',
    prompt: 'A table shows that when x = 1, 2, 3, the values of y are 5, 8, 11. If y = 3x + 2, what is y when x = 10?',
    choices: ['29', '30', '32', '35'],
    correctIndex: 2,
    explanation: 'y = 3(10) + 2 = 30 + 2 = 32.',
  },
  // Passport to Advanced Math
  {
    id: 'mock-m16',
    section: 'Math',
    topic: 'Exponents',
    difficulty: 'Easy',
    prompt: 'Simplify: (x³)(x⁴).',
    choices: ['x⁷', 'x¹²', 'x', 'x³⁴'],
    correctIndex: 0,
    explanation: 'When multiplying powers with the same base, add the exponents: 3 + 4 = 7, so x⁷.',
  },
  {
    id: 'mock-m17',
    section: 'Math',
    topic: 'Exponents',
    difficulty: 'Medium',
    prompt: 'If 3ˣ = 81, what is the value of x?',
    choices: ['3', '4', '5', '27'],
    correctIndex: 1,
    explanation: '81 = 3⁴, so x = 4.',
  },
  {
    id: 'mock-m18',
    section: 'Math',
    topic: 'Quadratics',
    difficulty: 'Medium',
    prompt: 'What are the solutions to x² − 7x + 10 = 0?',
    choices: ['x = 2 and x = 5', 'x = −2 and x = −5', 'x = 1 and x = 10', 'x = 3 and x = 4'],
    correctIndex: 0,
    explanation: 'Factor: (x − 2)(x − 5) = 0, so x = 2 or x = 5.',
  },
  {
    id: 'mock-m19',
    section: 'Math',
    topic: 'Quadratics',
    difficulty: 'Medium',
    prompt: 'The graph of y = (x − 3)² + 2 is a parabola. What are the coordinates of its vertex?',
    choices: ['(3, 2)', '(−3, 2)', '(3, −2)', '(2, 3)'],
    correctIndex: 0,
    explanation: 'In vertex form y = (x − h)² + k, the vertex is (h, k) = (3, 2).',
  },
  {
    id: 'mock-m20',
    section: 'Math',
    topic: 'Functions',
    difficulty: 'Medium',
    prompt: 'If f(x) = 2x² − 1, what is f(3)?',
    choices: ['11', '17', '35', '18'],
    correctIndex: 1,
    explanation: 'f(3) = 2(3²) − 1 = 2(9) − 1 = 18 − 1 = 17.',
  },
  {
    id: 'mock-m21',
    section: 'Math',
    topic: 'Functions',
    difficulty: 'Hard',
    prompt: 'If f(x) = x + 2 and g(x) = 3x, what is g(f(2))?',
    choices: ['8', '10', '12', '14'],
    correctIndex: 2,
    explanation: 'f(2) = 2 + 2 = 4. Then g(4) = 3 × 4 = 12.',
  },
  {
    id: 'mock-m22',
    section: 'Math',
    topic: 'Polynomials',
    difficulty: 'Medium',
    prompt: 'Which expression is equivalent to x² − 9?',
    choices: ['(x − 3)(x + 3)', '(x − 9)(x + 1)', '(x − 3)(x − 3)', '(x + 9)(x − 1)'],
    correctIndex: 0,
    explanation: 'This is a difference of squares: x² − 9 = (x − 3)(x + 3).',
  },
  // Geometry & Trigonometry
  {
    id: 'mock-m23',
    section: 'Math',
    topic: 'Geometry',
    difficulty: 'Easy',
    prompt: 'A rectangle has a length of 8 and a width of 5. What is its area?',
    choices: ['13', '26', '40', '45'],
    correctIndex: 2,
    explanation: 'Area of a rectangle = length × width = 8 × 5 = 40.',
  },
  {
    id: 'mock-m24',
    section: 'Math',
    topic: 'Circles',
    difficulty: 'Medium',
    prompt: 'A circle has a radius of 3. What is its area?',
    choices: ['3π', '6π', '9π', '12π'],
    correctIndex: 2,
    explanation: 'Area = πr² = π(3²) = 9π.',
  },
  {
    id: 'mock-m25',
    section: 'Math',
    topic: 'Circles',
    difficulty: 'Easy',
    prompt: 'A circle has a radius of 5. What is its circumference?',
    choices: ['5π', '10π', '25π', '20π'],
    correctIndex: 1,
    explanation: 'Circumference = 2πr = 2π(5) = 10π.',
  },
  {
    id: 'mock-m26',
    section: 'Math',
    topic: 'Geometry',
    difficulty: 'Easy',
    prompt: 'Two angles of a triangle measure 50° and 60°. What is the measure of the third angle?',
    choices: ['60°', '70°', '80°', '90°'],
    correctIndex: 1,
    explanation: 'Angles in a triangle sum to 180°. Third angle = 180 − 50 − 60 = 70°.',
  },
  {
    id: 'mock-m27',
    section: 'Math',
    topic: 'Geometry',
    difficulty: 'Medium',
    prompt: 'A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?',
    choices: ['10', '12', '14', '48'],
    correctIndex: 0,
    explanation: 'By the Pythagorean theorem: c = √(6² + 8²) = √(36 + 64) = √100 = 10.',
  },
  {
    id: 'mock-m28',
    section: 'Math',
    topic: 'Volume',
    difficulty: 'Easy',
    prompt: 'A rectangular box has dimensions 2 by 3 by 4. What is its volume?',
    choices: ['9', '18', '24', '29'],
    correctIndex: 2,
    explanation: 'Volume = length × width × height = 2 × 3 × 4 = 24.',
  },
  {
    id: 'mock-m29',
    section: 'Math',
    topic: 'Trigonometry',
    difficulty: 'Hard',
    prompt: 'In a right triangle, the side opposite angle θ is 5 and the hypotenuse is 13. What is sin(θ)?',
    choices: ['5/13', '12/13', '5/12', '13/5'],
    correctIndex: 0,
    explanation: 'sin(θ) = opposite / hypotenuse = 5/13.',
  },
  {
    id: 'mock-m30',
    section: 'Math',
    topic: 'Trigonometry',
    difficulty: 'Hard',
    prompt: 'In a right triangle, the side opposite angle θ is 3 and the side adjacent to θ is 4. What is tan(θ)?',
    choices: ['3/4', '4/3', '3/5', '4/5'],
    correctIndex: 0,
    explanation: 'tan(θ) = opposite / adjacent = 3/4.',
  },

  // ──────────────────── READING & WRITING (30) ────────────────────
  // Standard English Conventions — Boundaries
  {
    id: 'mock-r1',
    section: 'Reading & Writing',
    topic: 'Conjunctions',
    difficulty: 'Easy',
    prompt:
      'Which choice completes the text so that it conforms to the conventions of Standard English? "The museum was crowded, ___ we still enjoyed the exhibit."',
    choices: ['but', 'so', 'because', 'therefore'],
    correctIndex: 0,
    explanation: 'The two clauses contrast, so the coordinating conjunction "but" correctly joins them after the comma.',
  },
  {
    id: 'mock-r2',
    section: 'Reading & Writing',
    topic: 'Apostrophes',
    difficulty: 'Easy',
    prompt: 'Which choice completes the text correctly? "The committee released ___ final report on Friday."',
    choices: ['its', "it's", "its'", 'it is'],
    correctIndex: 0,
    explanation: '"Its" is the possessive form. "It\'s" means "it is," which does not fit here.',
  },
  {
    id: 'mock-r3',
    section: 'Reading & Writing',
    topic: 'Semicolons',
    difficulty: 'Medium',
    prompt: 'Which sentence is punctuated correctly?',
    choices: [
      'The experiment succeeded; the hypothesis was confirmed.',
      'The experiment succeeded, the hypothesis was confirmed.',
      'The experiment succeeded; and the hypothesis was confirmed.',
      'The experiment, succeeded; the hypothesis was confirmed.',
    ],
    correctIndex: 0,
    explanation: 'A semicolon correctly joins two independent clauses without a conjunction.',
  },
  {
    id: 'mock-r4',
    section: 'Reading & Writing',
    topic: 'Colons',
    difficulty: 'Medium',
    prompt: 'Which choice uses a colon correctly?',
    choices: [
      'She had one goal: to win the championship.',
      'She had: one goal to win the championship.',
      'She had one: goal to win the championship.',
      'She had one goal to: win the championship.',
    ],
    correctIndex: 0,
    explanation: 'A colon must follow a complete sentence and introduce an explanation. "She had one goal" stands alone.',
  },
  {
    id: 'mock-r5',
    section: 'Reading & Writing',
    topic: 'Punctuation',
    difficulty: 'Hard',
    prompt: 'Choose the correctly punctuated sentence.',
    choices: [
      "The author's first novel—published in 1995, won several awards.",
      "The author's first novel, published in 1995—won several awards.",
      "The author's first novel—published in 1995—won several awards.",
      "The author's first novel published in 1995—won several awards.",
    ],
    correctIndex: 2,
    explanation: 'A parenthetical phrase set off by dashes must use a dash on both sides for balanced punctuation.',
  },
  {
    id: 'mock-r6',
    section: 'Reading & Writing',
    topic: 'Joining clauses',
    difficulty: 'Medium',
    prompt: 'Which choice correctly joins the clauses? "The rain stopped ___ the sun came out."',
    choices: [', and', ', ', '; ', ' and'],
    correctIndex: 0,
    explanation: 'Two independent clauses are correctly joined by a comma followed by the coordinating conjunction "and."',
  },
  // Standard English Conventions — Form, Structure, and Sense
  {
    id: 'mock-r7',
    section: 'Reading & Writing',
    topic: 'Subject-verb agreement',
    difficulty: 'Medium',
    prompt: 'Which choice completes the text correctly? "The collection of rare coins ___ extremely valuable."',
    choices: ['is', 'are', 'were', 'have been'],
    correctIndex: 0,
    explanation: 'The subject is "collection" (singular). Ignore the phrase "of rare coins," so use "is."',
  },
  {
    id: 'mock-r8',
    section: 'Reading & Writing',
    topic: 'Pronoun agreement',
    difficulty: 'Medium',
    prompt: 'Which choice completes the text correctly? "Neither of the boys finished ___ homework."',
    choices: ['his', 'their', 'its', "they're"],
    correctIndex: 0,
    explanation: '"Neither" is singular, so it takes the singular pronoun "his."',
  },
  {
    id: 'mock-r9',
    section: 'Reading & Writing',
    topic: 'Modifiers',
    difficulty: 'Hard',
    prompt: 'Which choice completes the sentence correctly? "Running to catch the bus, ___."',
    choices: [
      "the keys fell from Maria's hand.",
      'Maria dropped her keys.',
      'her keys were dropped by Maria.',
      'the bus was almost missed by Maria.',
    ],
    correctIndex: 1,
    explanation: 'The introductory phrase "Running to catch the bus" must modify the person running, so "Maria" should follow the comma.',
  },
  {
    id: 'mock-r10',
    section: 'Reading & Writing',
    topic: 'Parallel structure',
    difficulty: 'Medium',
    prompt: 'Which choice keeps the list parallel? "The job requires reading, writing, and ___."',
    choices: ['to speak', 'speaking', 'speak', 'spoke'],
    correctIndex: 1,
    explanation: 'To match "reading" and "writing," the third item must also be a gerund: "speaking."',
  },
  {
    id: 'mock-r11',
    section: 'Reading & Writing',
    topic: 'Verb tense',
    difficulty: 'Medium',
    prompt: 'Which choice completes the text correctly? "By the time we arrived, the movie had already ___."',
    choices: ['began', 'begun', 'begin', 'beginning'],
    correctIndex: 1,
    explanation: 'After the helping verb "had," the past participle "begun" is required.',
  },
  {
    id: 'mock-r12',
    section: 'Reading & Writing',
    topic: 'Subject-verb agreement',
    difficulty: 'Easy',
    prompt: 'Which choice completes the text correctly? "Tom and Jerry ___ going to the store."',
    choices: ['is', 'are', 'was', 'has been'],
    correctIndex: 1,
    explanation: 'The compound subject "Tom and Jerry" is plural, so it takes the plural verb "are."',
  },
  {
    id: 'mock-r13',
    section: 'Reading & Writing',
    topic: 'Plural vs. possessive',
    difficulty: 'Medium',
    prompt: 'Which choice completes the text correctly? "The ___ uniforms were blue." (referring to multiple players)',
    choices: ['players', "player's", "players'", "players's"],
    correctIndex: 2,
    explanation: 'To show plural possession (uniforms belonging to multiple players), use "players\'" with the apostrophe after the s.',
  },
  {
    id: 'mock-r14',
    section: 'Reading & Writing',
    topic: 'Pronoun case',
    difficulty: 'Hard',
    prompt: 'Which choice completes the text in Standard English? "My brother is taller than ___."',
    choices: ['me', 'I', 'myself', 'mine'],
    correctIndex: 1,
    explanation: 'The implied verb is "am" (taller than I am), so the subject pronoun "I" is correct in formal English.',
  },
  // Transitions
  {
    id: 'mock-r15',
    section: 'Reading & Writing',
    topic: 'Transitions',
    difficulty: 'Medium',
    prompt: 'Which transition best fits? "The new policy promised lower costs; ___, expenses actually rose."',
    choices: ['however', 'therefore', 'moreover', 'likewise'],
    correctIndex: 0,
    explanation: 'The result contradicts the promise, so a contrast transition like "however" is needed.',
  },
  {
    id: 'mock-r16',
    section: 'Reading & Writing',
    topic: 'Transitions',
    difficulty: 'Medium',
    prompt: 'Which transition best fits? "It rained heavily; ___, the game was canceled."',
    choices: ['therefore', 'however', 'nevertheless', 'instead'],
    correctIndex: 0,
    explanation: 'The cancellation is a result of the rain, so a cause-and-effect transition like "therefore" fits.',
  },
  {
    id: 'mock-r17',
    section: 'Reading & Writing',
    topic: 'Transitions',
    difficulty: 'Easy',
    prompt: 'Which transition best fits? "The software is affordable; ___, it is easy to use."',
    choices: ['moreover', 'however', 'otherwise', 'regardless'],
    correctIndex: 0,
    explanation: 'The second clause adds a related benefit, so an additive transition like "moreover" fits.',
  },
  {
    id: 'mock-r18',
    section: 'Reading & Writing',
    topic: 'Transitions',
    difficulty: 'Easy',
    prompt: 'Which transition best fits? "Many fruits are rich in vitamin C; ___, oranges and strawberries are excellent sources."',
    choices: ['for example', 'however', 'therefore', 'in contrast'],
    correctIndex: 0,
    explanation: 'The second clause gives specific instances, so the example transition "for example" fits.',
  },
  // Craft and Structure — Words in Context
  {
    id: 'mock-r19',
    section: 'Reading & Writing',
    topic: 'Words in context',
    difficulty: 'Medium',
    prompt: 'Which word most logically completes the text? "The scientist\'s explanation was ___, leaving no room for confusion."',
    choices: ['lucid', 'obscure', 'confusing', 'vague'],
    correctIndex: 0,
    explanation: '"Leaving no room for confusion" signals clarity, which matches "lucid" (clear and easy to understand).',
  },
  {
    id: 'mock-r20',
    section: 'Reading & Writing',
    topic: 'Words in context',
    difficulty: 'Medium',
    prompt: 'Which word most logically completes the text? "Critics found the film ___, praising its fresh and original approach."',
    choices: ['derivative', 'innovative', 'ordinary', 'dull'],
    correctIndex: 1,
    explanation: 'Praise for a "fresh and original approach" matches "innovative."',
  },
  {
    id: 'mock-r21',
    section: 'Reading & Writing',
    topic: 'Words in context',
    difficulty: 'Medium',
    prompt: 'Which word most logically completes the text? "Her ___ tone suggested she doubted the salesperson\'s claims."',
    choices: ['trusting', 'skeptical', 'cheerful', 'generous'],
    correctIndex: 1,
    explanation: 'Doubt is best expressed by a "skeptical" tone.',
  },
  {
    id: 'mock-r22',
    section: 'Reading & Writing',
    topic: 'Words in context',
    difficulty: 'Hard',
    prompt: 'As used in the sentence, "ephemeral" most nearly means: "The fashion trend proved ephemeral, fading within months."',
    choices: ['permanent', 'short-lived', 'expensive', 'popular'],
    correctIndex: 1,
    explanation: '"Fading within months" defines the word in context: "ephemeral" means short-lived.',
  },
  // Information and Ideas — Central Ideas, Inference, Command of Evidence
  {
    id: 'mock-r23',
    section: 'Reading & Writing',
    topic: 'Command of evidence',
    difficulty: 'Hard',
    prompt:
      'A student claims that the city\'s new bike-share program reduced traffic congestion. Which finding, if true, would most directly support this claim?',
    choices: [
      'Residents reported that they enjoyed using the new bikes.',
      'Average car traffic on major roads fell 18% after the program launched.',
      'The program received a national award for its design.',
      'Bike-share programs exist in many other cities.',
    ],
    correctIndex: 1,
    explanation: 'A measured drop in car traffic directly tied to the program\'s launch is the strongest support for reduced congestion.',
  },
  {
    id: 'mock-r24',
    section: 'Reading & Writing',
    topic: 'Central ideas',
    difficulty: 'Medium',
    prompt:
      'Octopuses can change the color and texture of their skin in seconds, using this ability to hide from predators, communicate with other octopuses, and startle prey. Which choice best states the main idea?',
    choices: [
      'Octopuses are the most intelligent sea creatures.',
      "An octopus's skin is a remarkably versatile tool.",
      'Octopuses have many natural predators.',
      'Octopuses communicate only through color.',
    ],
    correctIndex: 1,
    explanation: 'The text lists several different uses of the skin, supporting the idea that it is a versatile tool.',
  },
  {
    id: 'mock-r25',
    section: 'Reading & Writing',
    topic: 'Inference',
    difficulty: 'Hard',
    prompt:
      'The ancient bridge had stood for 800 years, surviving floods and earthquakes. Yet within a decade of the new highway\'s construction nearby, cracks began to spread across its surface. Which choice most logically completes the text? The text most strongly suggests that ___.',
    choices: [
      'the bridge was poorly built originally',
      "the nearby construction likely contributed to the bridge's damage",
      'earthquakes are more damaging than highways',
      'the bridge will last another 800 years',
    ],
    correctIndex: 1,
    explanation: 'The damage appeared only after the nearby construction, implying the construction likely contributed to it.',
  },
  {
    id: 'mock-r26',
    section: 'Reading & Writing',
    topic: 'Rhetorical synthesis',
    difficulty: 'Medium',
    prompt:
      'A student wants to emphasize how quickly a town\'s population grew. Which choice best accomplishes this goal?',
    choices: [
      'The population changed over the years.',
      'The population grew from 5,000 to 50,000 in just five years.',
      'The population was studied by researchers.',
      'The population included many families.',
    ],
    correctIndex: 1,
    explanation: 'Specific figures and the phrase "in just five years" most effectively emphasize the rapid growth.',
  },
  {
    id: 'mock-r27',
    section: 'Reading & Writing',
    topic: 'Author\'s purpose',
    difficulty: 'Medium',
    prompt:
      'An author opens an essay with a vivid description of a polluted river choked with trash. The most likely purpose of this opening is to:',
    choices: [
      'entertain the reader with nature writing',
      'create an emotional appeal to highlight an environmental problem',
      'provide precise scientific data on water quality',
      'argue that rivers are unimportant',
    ],
    correctIndex: 1,
    explanation: 'A vivid, troubling image is a rhetorical move designed to make the reader feel the severity of the problem.',
  },
  {
    id: 'mock-r28',
    section: 'Reading & Writing',
    topic: 'Conciseness',
    difficulty: 'Medium',
    prompt: 'Which choice is most concise while keeping the meaning?',
    choices: [
      'Due to the fact that it was raining, we stayed inside.',
      'Because it was raining, we stayed inside.',
      'On account of the rain that was happening, we stayed inside.',
      'Owing to the fact of the rain, we stayed inside.',
    ],
    correctIndex: 1,
    explanation: '"Because" conveys the same cause-and-effect meaning without the wordy padding of the other options.',
  },
  {
    id: 'mock-r29',
    section: 'Reading & Writing',
    topic: 'Word choice',
    difficulty: 'Easy',
    prompt: 'Which choice completes the text in Standard English? "There were ___ cars on the road today than usual."',
    choices: ['less', 'fewer', 'least', 'lesser'],
    correctIndex: 1,
    explanation: '"Cars" are countable, so the comparative "fewer" is correct rather than "less."',
  },
  {
    id: 'mock-r30',
    section: 'Reading & Writing',
    topic: 'Pronoun case',
    difficulty: 'Medium',
    prompt: 'Which choice completes the text correctly? "To ___ should I address the complaint?"',
    choices: ['who', 'whom', 'whose', "who's"],
    correctIndex: 1,
    explanation: '"Whom" is the object of the preposition "to," so it is the correct form.',
  },
]

export interface MockTest {
  id: string
  name: string
  questions: PracticeQuestion[]
}

function shuffle<T>(arr: T[]): T[] {
  const out = [...arr]
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

/**
 * Builds 3 distinct, non-overlapping mock tests from the bank. Each test draws
 * 10 Math and 10 Reading & Writing questions, interleaved by section the way a
 * real SAT alternates content. The bank is shuffled on every call so repeat
 * visits produce a fresh distribution.
 */
export function buildMockTests(): MockTest[] {
  const math = shuffle(MOCK_BANK.filter((q) => q.section === 'Math'))
  const rw = shuffle(MOCK_BANK.filter((q) => q.section === 'Reading & Writing'))
  const perTest = 10

  const tests: MockTest[] = []
  for (let t = 0; t < 3; t++) {
    const m = math.slice(t * perTest, (t + 1) * perTest)
    const r = rw.slice(t * perTest, (t + 1) * perTest)
    const interleaved: PracticeQuestion[] = []
    const max = Math.max(m.length, r.length)
    for (let i = 0; i < max; i++) {
      if (m[i]) interleaved.push(m[i])
      if (r[i]) interleaved.push(r[i])
    }
    tests.push({
      id: `mock-test-${t + 1}`,
      name: `Practice Test ${t + 1}`,
      questions: interleaved,
    })
  }
  return tests
}
