'use client'

import type { Metadata } from 'next'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { MarketingShell } from '@/components/marketing/marketing-shell'
import { FadeInOnScroll } from '@/components/marketing/fade-in-on-scroll'
import { SITE } from '@/lib/site'

const FAQ_GROUPS = [
  {
    category: 'Getting started',
    faqs: [
      {
        q: 'Who is SAT Sage for?',
        a: 'Any student preparing for the SAT within the next 12 months. Whether you have a year to prepare or just one week, SAT Sage builds a plan tailored to exactly how much time you have left.',
      },
      {
        q: 'Is it really free?',
        a: `Yes. ${SITE.name} is completely free to use. There is no account required, no credit card, and no paywall. We built it because great SAT prep should not depend on how much money your family has.`,
      },
      {
        q: 'Do I need to create an account?',
        a: 'No. You can jump straight in and get your plan without signing up. Your answers stay in your browser. Creating an account does let you save your plan and come back to it later, though.',
      },
      {
        q: 'Can I join the waitlist before using the app?',
        a: 'Yes — join the waitlist to be first in line for new features, live coaching sessions, and study group updates. Your waitlist spot is free and instant.',
      },
    ],
  },
  {
    category: 'The study plan',
    faqs: [
      {
        q: 'How is my study plan built?',
        a: 'You answer a few questions: when your SAT is, how stressed you feel, and where you struggle most. Your AI coach analyzes your inputs and builds a day-by-day, prioritized plan that targets the topics with the highest score impact for you specifically.',
      },
      {
        q: 'How far out can I start using SAT Sage?',
        a: 'Up to 12 months before your SAT. The earlier you start, the more thorough and comprehensive your plan will be — covering foundations, strategy, and full mock tests. If you are last-minute, the plan shifts to a high-intensity sprint focused only on quick wins.',
      },
      {
        q: 'Will this actually raise my score?',
        a: 'No tool can guarantee points, but focused, high-yield review on your specific weak areas genuinely moves scores. Students who complete their plans and practice regularly see consistent improvement. We prioritize the topics most likely to move your score and keep you from burning out before test day.',
      },
      {
        q: 'Can I update my SAT date or change my weak areas?',
        a: "Yes. You can re-triage anytime and your plan will automatically recalibrate. If your test date changes or you feel more confident in a topic you flagged, just update it and we'll rebuild your priorities.",
      },
    ],
  },
  {
    category: 'Stress & wellbeing',
    faqs: [
      {
        q: 'What if I feel like I am panicking?',
        a: "Tap the panic button anytime. It walks you through a short breathing exercise and grounding reminders, then eases you back into your plan one small step at a time. You are not alone — this is literally what we designed the app for.",
      },
      {
        q: 'Is it okay to start prep even if I am already overwhelmed?',
        a: "Yes — especially then. SAT Sage is designed specifically for students who feel behind or overwhelmed. The triage form turns your stress level into a concrete plan, so you spend less time spiraling and more time making actual progress.",
      },
      {
        q: 'What if I run out of time the night before?',
        a: "The app has a Sprint Mode built for the final 24 hours. It strips everything down to only the highest-impact items, gives you a sleep deadline to protect your performance, and keeps sessions short so exhaustion doesn't tank your score.",
      },
    ],
  },
  {
    category: 'Content & accuracy',
    faqs: [
      {
        q: 'Is this affiliated with the College Board?',
        a: 'No. We are an independent study tool and are not affiliated with, endorsed by, or sponsored by the College Board. SAT is a registered trademark of the College Board.',
      },
      {
        q: 'Where do the practice questions come from?',
        a: 'Questions, explanations, and plans are generated by AI and curated from proven high-yield SAT topics. They are designed to closely mirror the real Digital SAT format and difficulty, but they are practice material — not official College Board exam questions.',
      },
      {
        q: 'Does the app cover the Digital SAT format?',
        a: 'Yes. All practice questions and study plans are aligned to the current Digital SAT format used since 2024, including the adaptive two-module structure for both Math and Reading & Writing.',
      },
    ],
  },
]

export default function FaqPage() {
  return (
    <MarketingShell>
      {/* Hero */}
      <section className="border-b border-border bg-background">
        <div className="mx-auto w-full max-w-3xl px-5 py-16 lg:px-8 lg:py-24">
          <FadeInOnScroll>
            <span className="text-sm font-bold uppercase tracking-wider text-primary">
              FAQ
            </span>
            <h1 className="mt-4 text-balance font-serif text-4xl font-normal tracking-tight lg:text-5xl">
              Everything you might be wondering
            </h1>
            <p className="mt-6 text-pretty text-lg leading-relaxed text-muted-foreground">
              Still have questions? Email us at{' '}
              <a
                href={`mailto:${SITE.supportEmail}`}
                className="font-medium text-primary underline-offset-2 hover:underline"
              >
                {SITE.supportEmail}
              </a>
            </p>
          </FadeInOnScroll>
        </div>
      </section>

      {/* FAQ groups */}
      <section>
        <div className="mx-auto w-full max-w-3xl px-5 py-16 lg:px-8 lg:py-24">
          <div className="flex flex-col gap-14">
            {FAQ_GROUPS.map((group) => (
              <FadeInOnScroll key={group.category}>
                <div className="flex flex-col gap-5">
                  <h2 className="text-xs font-bold uppercase tracking-widest text-primary">
                    {group.category}
                  </h2>
                  <motion.div
                    className="flex flex-col gap-3"
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true, amount: 0.1 }}
                    variants={{
                      visible: { transition: { staggerChildren: 0.05 } },
                    }}
                  >
                    {group.faqs.map((item) => (
                      <motion.details
                        key={item.q}
                        className="group cursor-pointer rounded-2xl border border-border bg-card p-5 transition-colors open:border-primary/40 hover:border-primary/20"
                        variants={{
                          hidden: { opacity: 0, x: -16 },
                          visible: { opacity: 1, x: 0, transition: { duration: 0.35 } },
                        }}
                      >
                        <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-base font-semibold">
                          {item.q}
                          <span
                            className="ti ti-plus shrink-0 text-lg text-primary transition-transform group-open:rotate-45"
                            aria-hidden="true"
                          />
                        </summary>
                        <p className="mt-3 text-pretty leading-relaxed text-muted-foreground">
                          {item.a}
                        </p>
                      </motion.details>
                    ))}
                  </motion.div>
                </div>
              </FadeInOnScroll>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-border bg-card/50">
        <div className="mx-auto w-full max-w-3xl px-5 py-14 lg:px-8 lg:py-20">
          <FadeInOnScroll>
            <div className="flex flex-col items-center gap-5 text-center">
              <h2 className="text-balance font-serif text-3xl font-normal tracking-tight">
                Still have questions?
              </h2>
              <p className="text-pretty text-lg leading-relaxed text-muted-foreground">
                Reach out and we will get back to you as fast as possible.
              </p>
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
                <a
                  href={`mailto:${SITE.supportEmail}`}
                  className="flex min-h-[52px] items-center justify-center gap-2 rounded-xl bg-primary px-7 text-base font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
                >
                  <span className="ti ti-mail text-lg" aria-hidden="true" />
                  Email us
                </a>
                <Link
                  href="/waitlist"
                  className="flex min-h-[52px] items-center justify-center gap-2 rounded-xl border border-border bg-card px-7 text-base font-semibold text-foreground transition-colors hover:bg-muted"
                >
                  Join the waitlist
                </Link>
              </div>
            </div>
          </FadeInOnScroll>
        </div>
      </section>
    </MarketingShell>
  )
}
